Features/i6 login
Ditlog-Dev/ditlog-webservice pull request #3
Opened 2018-03-03 14:03 UTC by gejimayu

Login done, including authentication with JWT

2018-03-03 14:12 UTC, rayandrews commented
could you please pull travis.yml from branch master? @gejimayu 
add if you could, make test case in package test in src. 👍 

cc : @deryrahman @keychera

2018-03-03 22:37 UTC, deryrahman requested changes

2018-03-03 22:37 UTC, deryrahman commented on src/main/resources/application.properties
> +# Oracle settings
you shouldn't push your config file. please use .gitignore

2018-03-03 22:37 UTC, deryrahman commented on src/main/java/id/ac/itb/logistik/ditlog/controller/UserController.java
> +        System.out.println(user.getUsername() + " " + user.getPassword());
don't forget to remove sys out println

2018-03-06 08:02 UTC, keychera requested changes
need some changes and unit tests first

2018-03-06 08:10 UTC, keychera commented on src/main/java/id/ac/itb/logistik/ditlog/DitlogApplication.java
> +	@Bean
commenting out this bean first because this hinder the unit testing

2018-03-06 09:11 UTC, keychera commented
the unit testing needs `application.properties` to properly run but that file is not (and should not be, right?) included in the commit hence Travis build is failing.

what could be the solution?

@rayandrews @deryrahman

2018-03-06 09:11 UTC, keychera submitted a review, later dismissed

2018-03-06 14:19 UTC, deryrahman commented
Hi, please update your branch. We've already push newest version on master @keychera @gejimayu

2018-03-06 14:29 UTC, keychera requested changes
need to update unit testing and merge the latest config files from master

2018-03-06 14:29 UTC, keychera commented on src/test/java/id/ac/itb/logistik/ditlog/DitlogUserServiceTests.java
> +
Change the testing to add its own test data to local db instead of using the production db

2018-03-06 14:29 UTC, keychera commented on build.gradle
need to update from the latest master

2018-03-06 14:40 UTC, keychera requested changes
Update the config stuff from master, modify the unit test, and do something to indicator feature in this branch

2018-03-06 14:40 UTC, keychera commented on src/main/java/id/ac/itb/logistik/ditlog/controller/IndicatorController.java
>  public class IndicatorController {
I think it's better to remove indicator feature in this branch

2018-03-07 09:42 UTC, rayandrews commented
test is still not correct @keychera 

__CAREFUL__ that test will be running alphabetically (like in Dictionary)

and please pull again (1 hour from now) from master to update the new config

2018-03-07 09:43 UTC, rayandrews commented
For testing, I will build BaseClass for testing.

I will update it to Master

2018-03-07 09:44 UTC, rayandrews commented
Whoops sorry, please use google checkstyle so there's no different style (minimize commit)

2018-03-07 17:09 UTC, keychera commented
@rayandrews the wrong tests are because of a programming mistake on my part, I just found them and fix it in the last commmit

and I still don't get any implication from the fact you've mentioned that the test will be run alphabetically

2018-03-07 17:41 UTC, keychera approved these changes

2018-03-07 17:43 UTC, keychera commented
the latest commit has arrived
build: `passing`
google checkstyle: `applied`
all: `is well`
I am kindly requesting your review

@rayandrews @deryrahman 

also, I haven't updated to master yet because I found no BaseClass for testing laready

2018-03-07 19:15 UTC, deryrahman approved these changes

2018-03-08 07:16 UTC, merged